name: CI/CD Pipeline

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - '*'

permissions:
  contents: write

jobs:
  check_merge_conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check merge conflicts
        run: echo "Checking merge conflicts..."

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: lint
        run: echo "Running lint checks..."
