name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: write

jobs:
  check_merge_conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check merge conflicts
        run: echo "Checking merge conflicts..."

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: lint
        run: echo "Running lint checks..."

  tag_version:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check for .version file
        id: check_version
        run: |
          if [ ! -f .version ]; then
            echo "WARNING: The .version file does not exist in this commit."
            exit 0
          fi
      - name: Read version
        id: read_version
        run: |
          VERSION=$(cat .version)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Set up git config
        run: |
          git config user.name "JhonesYure"
          git config user.email "jymbomfim@hotmail.com"
      - name: Fetch tags
        run: git fetch --tags origin
      - name: Create and push tag
        run: |
          VERSION="${{ steps.read_version.outputs.version }}"
          if git tag -l | grep -q "^${VERSION}$"; then
            echo "Tag ${VERSION} already exists. Skipping tag creation."
          else
            echo "Creating and pushing tag ${VERSION}..."
            git tag -a "${VERSION}" -m "Release ${VERSION}"
            git push origin "${VERSION}"
          fi
